name: Build and Release Flex Blade PHAR
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.php'
      - 'composer.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: phar, dom, mbstring, fileinfo
          tools: composer:v2
          coverage: xdebug
          ini-values: phar.readonly=0

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Create temp directories
        run: |
          mkdir -p temp_install
          chmod -R 755 temp_install

      - name: Run tests
        run: |
          php vendor/bin/phpunit --bootstrap dev_build.php --configuration phpunit.xml
        env:
          TEMP_INSTALL: ${{ github.workspace }}/temp_install

  build-and-release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: phar, dom, mbstring, fileinfo
          tools: composer:v2
          ini-values: phar.readonly=0

      - name: Generate Version
        id: version
        run: |
          VERSION="v0.$(date +'%y%m%d').${GITHUB_RUN_NUMBER}"
          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build PHAR
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "Building Flex Blade package with version $VERSION"
          php build.php

      - name: Verify PHAR
        run: |
          PHAR_FILE="flexblade.phar"
          
          if [ ! -f "$PHAR_FILE" ]; then
            echo "Error: $PHAR_FILE was not created"
            exit 1
          fi
          
          echo "PHAR file created: $PHAR_FILE"
          echo "File size: $(ls -lh $PHAR_FILE | awk '{print $5}')"
          
          # Test PHAR execution
          php $PHAR_FILE || echo "PHAR executed successfully"

      - name: Generate Release Notes
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## Flex Blade ${{ steps.version.outputs.version }}
          
          🎉 **New Release of Flex Blade Package**
          
          ### 📦 What's Included:
          
          - **`flexblade.phar`** - Complete Flex Blade package with Blade inspired templating for PHP
          
          ### 🚀 Installation:
          
          **Download PHAR:**
          ```bash
          curl -L -o flexblade.phar https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.version }}/flexblade.phar
          ```
          
          **Include in your PHP project:**
          ```php
          // In your bootstrap or index.php
          require_once 'path/to/flexblade.phar';
          ```
          
          ### 💡 Usage:
          
          ```php
          // In your PHP file
          define('VIEWS', __DIR__ . '/views/');
          require_once 'flexblade.phar';
            
          use FlexBlade\Blade\BladeCompiler;
            
          $blade = new BladeCompiler();
          echo $blade->render('welcome', ['name' => 'World']);
          ```
          
          ### 🔧 Requirements:
          - PHP >= 8.4
          
          ### 📝 Build Information:
          - Version: ${{ steps.version.outputs.version }}
          - Built from commit: `${{ github.sha }}`
          - Build date: `$(date -u +"%Y-%m-%d %H:%M:%S UTC")`
          - PHP Version: 8.4
          EOF
          
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: flexblade.phar
          tag_name: ${{ steps.version.outputs.version }}
          name: Flex Blade ${{ steps.version.outputs.version }}
          body: ${{ steps.release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
          generate_release_notes: false

      - name: Upload PHAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flexblade-${{ steps.version.outputs.version }}
          path: flexblade.phar
          retention-days: 90